--1. LOADING DATASET WITH PRIMARY KEY TO ORDER_DATE COLUMN.

create or replace table ST_SALES 
( order_id varchar(30),
  order_date date PRIMARY KEY,
  ship_date date,
  ship_mode varchar(30),
  customer_name varchar(30),
  segment varchar(30),
  state varchar(100),	
  country varchar(60),	
  market varchar(30),
  region varchar(30),
  product_id varchar(40),	
  category varchar(30),
  sub_category varchar(30),
  product_name varchar(200),	
  sales number(20),
  quantity number(20),
  discount number(20),	
  profit number(20),
  shipping_cost number(20),	
  order_priority varchar(30),	
  year number(10));

describe table ST_SALES;

select * from ST_SALES;

CREATE OR REPLACE TABLE ST_SALES_COPY_DATA AS SELECT * FROM ST_SALES;
SELECT * FROM ST_SALES_COPY_DATA;
DESCRIBE TABLE ST_SALES_COPY_DATA;


-- 2. APPLING PRIMARY KEY ON ORDER_ID

ALTER TABLE ST_SALES_COPY_DATA DROP PRIMARY KEY;

ALTER TABLE ST_SALES_COPY_DATA ADD PRIMARY KEY(ORDER_ID);


--3. QUESTION NOT CORRECT--[MAM SAID NOT TO SOLVE]


--4. CREATE A NEW COLUMN CALLED ORDER_EXTRACT AND EXTRACT THA NUMBER AFTER THE LAST '-' FROM ORDER ID COLUMN.

SELECT SPLIT_PART(ORDER_ID,'-',3) AS ORDER_EXTRACT FROM ST_SALES_COPY_DATA;


--5. CREATE A NEW COLUMN CALLED DISCOUNT FLAG AND CATEGORIZE IT BASED ON DISCOUNT.USE 'YES'IF THE DISCOUNT IS GREATER THEN ZERO ELSE 'NO'.

SELECT *,
        CASE
            WHEN DISCOUNT > 0 THEN 'YES'
            ELSE 'NO'
        END AS DISCOUNT_FLAG
FROM  ST_SALES_COPY_DATA;       

--6.FIND OUT HOW MUCH DAYS TAKEN FOR EACH ORDER TO PROCESS FOR THE SHIPMENT FOR EVERY ORDER ID.

SELECT DATEDIFF(DAY,ORDER_DATE,SHIP_DATE) AS PROCESS_DAY FROM ST_SALES_COPY_DATA;

--7 THE PROCESS DAY AS BY RATING IF IT TAKES LESS OR EQUAL 3  DAYS MAKE 5,LESS OR EQUAL THAN 6 DAYS BUT MORE THAN 3 MAKE 4,LESS THAN 10 BUT MORE THAN 6 MAKE 3,MORE THAN 10 MAKE IT 2 FOR EVERY ORDER ID.

SELECT *,
        CASE
           WHEN DATEDIFF(DAY,ORDER_DATE,SHIP_DATE) <= 3 THEN 5
           WHEN DATEDIFF(DAY,ORDER_DATE,SHIP_DATE)  >3 AND DATEDIFF(DAY,ORDER_DATE,SHIP_DATE)  <= 6 THEN 4
           WHEN DATEDIFF(DAY,ORDER_DATE,SHIP_DATE)  > 6 AND DATEDIFF(DAY,ORDER_DATE,SHIP_DATE)  < 10 THEN 3
           ELSE 2
        END AS RATING_TYPE
FROM ST_SALES_COPY_DATA;
